version: '3'
services:
  webapp:
    image: json_api
    build: ./webapp
    ports:
      - $PORT:$PORT
    depends_on:
      - "database"
    environment:
      - DB_HOSTNAME=$DB_HOSTNAME
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_DATABASE=$DB_DATABASE
      - DB_TABLE=$DB_TABLE
      - DB_SSLMODE=$DB_SSLMODE

  database:
    image: postgres:alpine
    ports:
      - $DBPORT:$DBPORT
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_DATABASE
